/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NextGenGaming.Game;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Lenovo Ideapad
 */
public class SweeperPanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form SweeperPanel
     */
    private static int remainingSeconds;
    
    public SweeperPanel() {
        initComponents();
        initializeTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ImageIcon homeIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\icons8-home (1).gif").getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT));
        jButton1.setIcon(homeIcon);
        jButton2 = new javax.swing.JButton();
        ImageIcon saveIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\icons8-save.gif").getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT));
        jButton2.setIcon(saveIcon);
        jButton3 = new javax.swing.JButton();
        ImageIcon restartIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\icons8-restart.gif").getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT));
        jButton3.setIcon(restartIcon);
        jButton4 = new javax.swing.JButton();
        ImageIcon orangeIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\orange.png").getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
        jButton4.setIcon(orangeIcon);
        jButton5 = new javax.swing.JButton();
        ImageIcon blueIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\blue.png").getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
        jButton5.setIcon(blueIcon);
        jButton6 = new javax.swing.JButton();
        ImageIcon redIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\red.png").getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
        jButton6.setIcon(redIcon);
        jButton7 = new javax.swing.JButton();
        ImageIcon greyIcon = new ImageIcon(new ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\grey.png").getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
        jButton7.setIcon(greyIcon);
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 102, 0));
        setForeground(new java.awt.Color(204, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 90));

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 90));

        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, 90));

        jButton4.setBackground(new Color(0,0,0,70));
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, 70));

        jButton5.setBackground(new Color(0,0,0,70));
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 80, 70));

        jButton6.setBackground(new Color(0,0,0,70));
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 80, 70));

        jButton7.setBackground(new Color(0,0,0,70));
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 80, 70));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 3));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 270, 90));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abdullah Khan\\Desktop\\asjad\\asjad\\src\\main\\java\\asjad\\highScore.png")); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 90, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void initializeTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                seconds++;
                updateTimerLabel();
            }
        });
    }

    public void startTimer() {
        if (!running) {
            timer.start();
            running = true;
        }
    }

    public void stopTimer() {
        if (running) {
            timer.stop();
            running = false;
        }
    }

    public void resetTimer() {
        seconds = 0;
        updateTimerLabel();
    }

    private void updateTimerLabel() {
        int minutes = seconds / 60;
        remainingSeconds = seconds % 60;
        jLabel1.setText(String.format("%02d:%02d", minutes, remainingSeconds));
    }
        public void startMineSweeperTimer() {
        startTimer();
    }

    public void stopMineSweeperTimer() {
        stopTimer();
    }

    public void resetMineSweeperTimer() {
        resetTimer();
    }
    public static int getSecond(){
        return remainingSeconds;
    }
    
    
    
    private Timer timer;
    private int seconds = 0;
    private boolean running = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
      
    }
}
